'use client';
import {createClient} from '@supabase/supabase-js';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {contentFields,availableCategories,categoryKey,type SiteSettings} from '@/lib/site-content';
import type {Project} from '@/lib/portfolio';
const empty:Project={id:'',title:'',category:'websites',description:'',image:'',url:'',position:1,published:1,featured:1};
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{id:string;name:string}[]}){return <label>{label}<Select value={value||'none'} onValueChange={v=>onChange(v==='none'?'':v)}><SelectTrigger aria-label={label} className="admin-select"><SelectValue/></SelectTrigger><SelectContent className="admin-select-options">{options.map(c=><SelectItem key={c.id||'none'} value={c.id||'none'}>{c.name}</SelectItem>)}</SelectContent></Select></label>}
export default function Editor({initial,settings}:{initial:Project[];settings:SiteSettings}){
 const [projects,setProjects]=useState(initial),[config,setConfig]=useState<SiteSettings>({...settings,categories:availableCategories(settings,initial)}),[draft,setDraft]=useState<Project>({...empty}),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[projectDirty,setProjectDirty]=useState(false),[configDirty,setConfigDirty]=useState(false),[persisted,setPersisted]=useState<SiteSettings>(settings),[categoryName,setCategoryName]=useState('');
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(projectDirty||configDirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[projectDirty,configDirty]);
 const edit=(p:Project)=>{if(projectDirty&&!window.confirm('Descartar as alterações deste projeto que ainda não foram guardadas?'))return;setProjectDirty(false);setDraft({...p,category:categoryKey(p)});setStatus('')};const field=(k:keyof Project,v:string|number)=>{setDraft(d=>({...d,[k]:v}));setProjectDirty(true)};
 const change=(next:SiteSettings)=>{setConfig(next);setConfigDirty(true)};
 async function upload(f:File|undefined,set:(path:string)=>void){if(!f)return;if(f.size>8*1024*1024){setStatus('Use uma imagem até 8 MB.');return}setBusy(true);setStatus('A enviar imagem…');try{const r=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:f.type,size:f.size})});const j=await r.json() as {error?:string;image:string;path:string;token:string;bucket:string;url:string;key:string};if(!r.ok)throw Error(j.error||'Não foi possível enviar.');const storage=createClient(j.url,j.key,{auth:{persistSession:false,autoRefreshToken:false}}).storage;const {error}=await storage.from(j.bucket).uploadToSignedUrl(j.path,j.token,f,{contentType:f.type});if(error)throw Error('O upload falhou. Tente novamente.');set(j.image);setStatus('Imagem pronta. Guarde para aplicar ao site.')}catch(e){setStatus(e instanceof Error?e.message:'O upload falhou.')}finally{setBusy(false)}}
 async function saveProject(e:React.FormEvent){e.preventDefault();if(!draft.image){setStatus('Adicione uma capa.');return}setBusy(true);try{const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const j=await r.json() as {error?:string;image:string;id:string};if(!r.ok)throw Error(j.error||'Não foi possível guardar.');const saved={...draft,id:j.id};setDraft(saved);setProjects(ps=>[...ps.filter(p=>p.id!==saved.id),saved].sort((a,b)=>a.position-b.position));setStatus('Projeto guardado. A página inicial mostra até seis destaques por categoria.');setProjectDirty(false)}catch(e){setStatus(e instanceof Error?e.message:'Não foi possível guardar.')}finally{setBusy(false)}}
 async function saveSettings(scope:'categories'|'content'){const next=scope==='categories'?{...persisted,categories:config.categories}:{...config,categories:persisted.categories};setBusy(true);setStatus('A guardar configurações…');try{const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const j=await r.json() as {error?:string;image:string;id:string};if(!r.ok)throw Error(j.error||'Não foi possível guardar.');setStatus('Configurações publicadas.');setPersisted(next);setConfigDirty(JSON.stringify(config)!==JSON.stringify(next))}catch(e){setStatus(e instanceof Error?e.message:'Não foi possível guardar.')}finally{setBusy(false)}}
 const visibleHome=projects.filter(p=>p.published&&p.featured!==0&&categoryKey(p)===draft.category).sort((a,b)=>a.position-b.position).slice(0,6);
 const imageControl=(key:'heroImage'|'backgroundImage'|'studioImage',label:string)=><div className="cms-image-field" key={key}><label>{label}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>upload(e.target.files?.[0],path=>change({...config,[key]:path}))}/></label>{config[key]&&<img src={config[key]} alt={label}/>}<button type="button" onClick={()=>{if(key==='studioImage')change({...config,studioImage:''})}} hidden={key!=='studioImage'||!config[key]}>Usar composição original</button></div>;
 const projectOptions=[{id:'',name:'Não mostrar projeto'},...projects.filter(p=>p.published).map(p=>({id:p.id,name:p.title}))];
 return <main className="admin cms"><header className="admin-head"><img src="/assets/wordmark.92634bce5b.svg" alt="Crisora"/><a href="/" target="_blank" rel="noopener">Ver site ↗</a></header><h1>A Crisora, nas suas mãos.</h1><p>Capas, projetos, categorias e conteúdo. As alterações entram no site ao guardar.</p><p className="cms-status" role="status">{status}</p>
 <Tabs defaultValue="projects"><TabsList className="cms-tabs"><TabsTrigger value="projects">Projetos</TabsTrigger><TabsTrigger value="categories">Categorias</TabsTrigger><TabsTrigger value="content">Conteúdo do site</TabsTrigger></TabsList>
 <TabsContent value="projects"><div className="admin-layout"><aside className="admin-list"><button className="new-project" disabled={busy} onClick={()=>edit({...empty,category:persisted.categories[0].id,position:Math.max(0,...projects.map(p=>p.position))+1})}>+ Novo projeto</button>{projects.map(p=><button key={p.id} disabled={busy} aria-pressed={draft.id===p.id} onClick={()=>edit(p)}><img src={p.image} alt=""/><span>{p.title}<small>{config.categories.find(c=>c.id===categoryKey(p))?.name} · {p.published?'Publicado':'Rascunho'} · Ordem {p.position}</small></span></button>)}</aside>
 <form className="admin-form" onSubmit={saveProject}><label>Título<input required maxLength={150} value={draft.title} onChange={e=>field('title',e.target.value)}/></label><Choice label="Categoria" value={draft.category} onChange={v=>field('category',v)} options={persisted.categories}/><label>Sobre o projeto<textarea required maxLength={3000} value={draft.description} onChange={e=>field('description',e.target.value)}/></label><label>Link do projeto (opcional)<input type="url" value={draft.url} onChange={e=>field('url',e.target.value)} placeholder="https://…"/></label><label>Capa do projeto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>upload(e.target.files?.[0],path=>field('image',path))}/></label><p className="admin-note">Esta imagem será a capa exibida no site, sem mockup automático. JPG, PNG ou WebP, até 8 MB. A imagem inteira é preservada.</p>{draft.image&&<img className="cms-cover-preview" src={draft.image} alt="Prévia da capa"/>}<div className="form-pair"><label>Ordem na categoria<input required type="number" min="0" max="999" value={draft.position} onChange={e=>field('position',Number(e.target.value))}/></label><Choice label="Visibilidade" value={String(draft.published)} onChange={v=>field('published',Number(v))} options={[{id:'1',name:'Publicado'},{id:'0',name:'Rascunho (oculto)'}]}/></div><label className="cms-check"><Checkbox checked={draft.featured!==0} onCheckedChange={v=>field('featured',v===true?1:0)}/>Destacar na página inicial</label><p className="admin-note">Até seis por categoria, pela ordem indicada. Os restantes continuam no portfólio completo. Projetos em rascunho não aparecem no site.</p><p className="admin-note">Destaques guardados nesta categoria: {visibleHome.map(p=>p.title).join(' · ')||'Nenhum'}.</p><button className="submit" disabled={busy}>{busy?'A guardar…':'Guardar projeto'}</button></form></div></TabsContent>
 <TabsContent value="categories"><section className="cms-panel"><h2>Categorias do portfólio</h2><p>O nome e a ordem abaixo definem as abas do site. Renomear mantém os projetos associados.</p>{config.categories.map((c,i)=><div className="cms-category" key={c.id}><label>Nome<input aria-label={'Nome da categoria '+(i+1)} value={c.name} maxLength={60} onChange={e=>change({...config,categories:config.categories.map(x=>x.id===c.id?{...x,name:e.target.value}:x)})}/></label><span>{projects.filter(p=>categoryKey(p)===c.id).length} projetos</span><button disabled={i===0} aria-label={'Mover '+c.name+' para cima'} onClick={()=>{const a=[...config.categories];[a[i-1],a[i]]=[a[i],a[i-1]];change({...config,categories:a})}}>↑</button><button disabled={i===config.categories.length-1} aria-label={'Mover '+c.name+' para baixo'} onClick={()=>{const a=[...config.categories];[a[i+1],a[i]]=[a[i],a[i+1]];change({...config,categories:a})}}>↓</button><button disabled={config.categories.length===1||projects.some(p=>categoryKey(p)===c.id)} onClick={()=>change({...config,categories:config.categories.filter(x=>x.id!==c.id)})}>Remover</button></div>)}<p className="admin-note">Para remover uma categoria, primeiro mova os projetos dela para outra.</p><div className="cms-category"><input aria-label="Nova categoria" placeholder="Ex.: Fotografia" value={categoryName} maxLength={60} onChange={e=>setCategoryName(e.target.value)}/><button disabled={!categoryName.trim()||config.categories.length>=30} onClick={()=>{if(config.categories.some(c=>c.name.toLowerCase()===categoryName.trim().toLowerCase())){setStatus('Já existe uma categoria com esse nome.');return}change({...config,categories:[...config.categories,{id:crypto.randomUUID(),name:categoryName.trim()}]});setCategoryName('')}}>Adicionar categoria</button></div><button className="submit" disabled={busy} onClick={()=>saveSettings('categories')}>Guardar categorias</button><p className="admin-note">Guarde as categorias antes de as usar num projeto.</p></section></TabsContent>
 <TabsContent value="content"><section className="cms-panel"><h2>Imagens e fundos</h2><p>Troque as imagens mantendo a composição, o escurecimento e os movimentos do site.</p><div className="cms-image-grid">{imageControl('heroImage','Imagem de abertura')}{imageControl('backgroundImage','Textura do fundo contínuo')}{imageControl('studioImage','Imagem da seção A Crisora (opcional)')}</div></section><section className="cms-panel"><h2>Projetos na apresentação dos serviços</h2><Choice label="Exemplo de website" value={config.websiteProject} onChange={v=>change({...config,websiteProject:v})} options={projectOptions}/><Choice label="Exemplo de identidade" value={config.identityProject} onChange={v=>change({...config,identityProject:v})} options={projectOptions}/>{[0,1,2].map(i=><Choice key={i} label={'Capa de comunicação '+(i+1)} value={config.socialProjects[i]||''} onChange={v=>{const a=[...config.socialProjects];a[i]=v;change({...config,socialProjects:a})}} options={projectOptions}/>)}</section>
 {[...new Set(contentFields.map(([group])=>group))].map(group=><section className="cms-panel" key={group}><h2>{group}</h2>{contentFields.filter(([g])=>g===group).map(([,key,label])=><label key={key}>{label}<textarea rows={key.toLowerCase().includes('description')?3:2} maxLength={3000} value={config.text[key]} onChange={e=>change({...config,text:{...config.text,[key]:e.target.value}})}/></label>)}</section>)}
 {(['process','faq'] as const).map(key=><section className="cms-panel" key={key}><h2>{key==='faq'?'Perguntas frequentes':'Como trabalhamos'}</h2>{config[key].map((pair,i)=><div className="cms-pair" key={i}>{pair.map((value,j)=><label key={j}>{j===0?(key==='faq'?'Pergunta':'Etapa'):'Texto'}<textarea value={value} maxLength={3000} onChange={e=>change({...config,[key]:config[key].map((p,n)=>n===i?p.map((v,k)=>k===j?e.target.value:v):p)})}/></label>)}<button disabled={key==='process'&&config[key].length===1} onClick={()=>change({...config,[key]:config[key].filter((_,n)=>n!==i)})}>Remover {key==='faq'?'pergunta':'etapa'}</button></div>)}<button disabled={config[key].length>=(key==='faq'?12:8)} onClick={()=>change({...config,[key]:[...config[key],['','']]})}>Adicionar {key==='faq'?'pergunta':'etapa'}</button></section>)}<button className="submit cms-save" disabled={busy} onClick={()=>saveSettings('content')}>{busy?'A guardar…':'Guardar conteúdo do site'}</button></TabsContent></Tabs></main>
}
