'use client';
import {defaultSettings,categoryKey,type SiteSettings} from '@/lib/site-content';
import {useRef,useState} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {ArrowUpRight,ArrowDown,ArrowRight,Plus,Minus,Menu as MenuIcon} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {PortfolioGallery} from './portfolio-gallery';
import {SiteHeader} from './site-header';
import {ProjectStage} from './project-stage';
import {ServiceJourney} from './service-journey';
import {TextureContinuity} from './texture-continuity';
import {AmbientFlow} from './ambient-flow';
import {LivingSurface} from './living-surface';
import {MotionDecor,RevealTitle,useMotionSystem} from './motion-system';
import {discipline,projectMeta,type Project} from '@/lib/portfolio';
const ease=[.16,1,.3,1] as const;

export default function Experience({projects,settings=defaultSettings}:{projects:Project[];settings?:SiteSettings}){const root=useRef<HTMLDivElement>(null);const [menu,setMenu]=useState(false),[selected,setSelected]=useState<Project|null>(null),[closing,setClosing]=useState(false),[privacy,setPrivacy]=useState(false),[faq,setFaq]=useState<number|null>(null),[status,setStatus]=useState('');const reduced=useReducedMotion();const lenis=useMotionSystem(root,menu||!!selected||privacy);
function openProject(p:Project){setClosing(false);setSelected(p)}function closeProject(){if(reduced){setSelected(null);return}setClosing(true)}function brief(form:HTMLFormElement){const f=new FormData(form);return `Olá, Crisora!\n\nNome: ${f.get('name')}\nEmpresa: ${f.get('company')||'Não indicada'}\nEmail: ${f.get('email')}\n\n${f.get('message')}`}
return <div className="creative-site" ref={root}><MotionDecor/><AmbientFlow/><TextureContinuity src={settings.backgroundImage}/><a className="skip" href="#projetos">Ir para os projetos</a><SiteHeader onMenu={()=>setMenu(true)}/>
<main><section className="reveal-opening" id="inicio"><LivingSurface src={settings.heroImage}/><div className="opening-shade"/><div className="opening-mark" aria-hidden="true"><img src="/assets/symbol.577505649d.svg" alt=""/></div><div className="opening-message"><p className="opening-label">{settings.text.heroLabel}</p><h1><span><i>{settings.text.heroLine1}</i></span><span><i>{settings.text.heroLine2}</i></span></h1><p className="opening-subtitle">{settings.text.heroSubtitle}</p></div><a href="#servicos" className="opening-cue"><span>DESLIZE PARA DESCOBRIR</span><ArrowDown size={20}/></a></section>
<div id="flow-content"><ServiceJourney settings={settings} projects={projects} onOpen={openProject}/>
<section className="project-library section" id="projetos"><div className="library-heading"><p className="eyebrow">DA IDEIA À PRESENÇA</p><RevealTitle lines={[settings.text.portfolioTitle]}/><p>{settings.text.portfolioDescription}</p></div><PortfolioGallery settings={settings} projects={projects} onOpen={openProject}/></section>
<section className="studio section" id="sobre"><div className="studio-identity">{settings.studioImage?<img className="studio-upload" src={settings.studioImage} alt="A Crisora"/>:<div><img src="/assets/symbol.577505649d.svg" alt="Símbolo da Crisora"/><div className="studio-words" aria-label="Clareza, estrutura, percepção">{["CLAREZA","ESTRUTURA","PERCEPÇÃO"].map(word=><span key={word}><b>{word}</b></span>)}</div></div>}</div><div className="studio-copy"><p className="eyebrow">04 / A CRISORA</p><RevealTitle lines={[settings.text.studioLine1,settings.text.studioLine2]}/><p>{settings.text.studioDescription1}</p><p>{settings.text.studioDescription2}</p><a className="animated-link" href="#contacto">Conte-nos sobre a sua marca <ArrowUpRight size={18}/></a></div></section>
<section className="process section"><div className="process-heading"><p className="eyebrow">05 / COMO TRABALHAMOS</p><RevealTitle lines={['Próximos passos.','Sem complicar.']}/></div><div className="process-steps">{settings.process.map(([t,d],i)=><article key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
<section className="faq section"><div><p className="eyebrow">ANTES DE COMEÇAR</p><RevealTitle lines={['Talvez esteja','a pensar nisto.']}/></div><div>{settings.faq.map(([q,a],i)=><article key={q}><button aria-expanded={faq===i} aria-controls={'faq-'+i} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={18}/>:<Plus size={18}/>}</button><AnimatePresence initial={false}>{faq===i&&<motion.div id={'faq-'+i} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:reduced?0:.35,ease}} style={{overflow:'hidden'}}><p>{a}</p></motion.div>}</AnimatePresence></article>)}</div></section>
<section className="contact section" id="contacto"><div className="contact-title"><p className="eyebrow">O PRÓXIMO CAPÍTULO PODE COMEÇAR AQUI.</p><RevealTitle lines={[settings.text.contactLine1,settings.text.contactLine2]}/></div><div className="contact-grid grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-24"><div><p>{settings.text.contactDescription}</p><a className="contact-instagram" data-magnetic href={settings.text.contactInstagram} target="_blank" rel="noopener">Conversar no Instagram <ArrowUpRight size={23}/></a><a className="email" href={"mailto:"+settings.text.contactEmail}>{settings.text.contactEmail}</a><span className="contact-locale">{settings.text.contactLocale}</span></div><form onSubmit={e=>{e.preventDefault();location.href='mailto:'+settings.text.contactEmail+'?subject=Novo%20projeto%20Crisora&body='+encodeURIComponent(brief(e.currentTarget));setStatus('Pedido preparado. Conclua o envio no seu aplicativo de email.')}}><div className="form-pair grid grid-cols-1 sm:grid-cols-2 gap-x-6"><label>Nome<input required name="name" autoComplete="name" placeholder="O seu nome" maxLength={100}/></label><label>Empresa<input name="company" autoComplete="organization" placeholder="Nome da empresa" maxLength={150}/></label></div><label>Email<input required type="email" name="email" autoComplete="email" placeholder="O seu email"/></label><label>Sobre o projeto<textarea required name="message" maxLength={3000} placeholder="O que tem em mente?"/></label><div className="form-actions"><button type="submit" className="submit" data-magnetic>Preparar pedido <ArrowUpRight size={19}/></button><button className="copy-button" type="button" onClick={async e=>{const f=e.currentTarget.closest('form')!;if(!f.reportValidity())return;try{await navigator.clipboard.writeText(brief(f));setStatus('Mensagem copiada. Pode colá-la na conversa pelo Instagram.')}catch{setStatus('Não foi possível copiar. Use o email ou contacte-nos pelo Instagram.')}}}>Copiar mensagem</button></div><small>Abre o seu aplicativo de email. O envio é concluído por si.</small><p role="status">{status}</p></form></div></section></div></main>
<footer className="compact-footer"><div className="footer-bottom"><span>© {new Date().getFullYear()} Crisora</span><span>DESIGN COM DIREÇÃO.</span><button onClick={()=>setPrivacy(true)}>Privacidade</button><a href="/admin">Área de gestão</a><a href="#inicio" className="animated-link">Voltar ao início <ArrowUpRight size={14}/></a></div></footer>
<Dialog open={menu} onOpenChange={setMenu}><DialogContent className="menu-panel" data-lenis-prevent><DialogTitle className="eyebrow">CRISORA</DialogTitle><DialogDescription className="sr-only">Explore as seções do site.</DialogDescription><motion.div initial={reduced?false:{y:30,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.65,ease}}>{[['01','O que fazemos','servicos'],['02','Projetos','projetos'],['03','A Crisora','sobre'],['04','Vamos conversar','contacto']].map(([n,t,id])=><a href={'#'+id} key={id} onClick={e=>{e.preventDefault();setMenu(false);setTimeout(()=>{lenis.current?.start();if(lenis.current)lenis.current.scrollTo('#'+id,{force:true});else document.getElementById(id)?.scrollIntoView()},0)}}><small>{n}</small><span>{t}</span><ArrowUpRight/></a>)}<a href="/portfolio" target="_blank" rel="noopener" onClick={()=>setMenu(false)}><small>05</small><span>Portfólio completo</span><ArrowUpRight/></a></motion.div><p>Brasil & Portugal · Atendimento online</p></DialogContent></Dialog>
<Dialog open={!!selected} onOpenChange={v=>!v&&closeProject()}><DialogContent className="project-modal" data-lenis-prevent>{selected&&<motion.div initial={reduced?false:{clipPath:'inset(100% 0 0 0)',y:30}} animate={closing?{clipPath:'inset(0 0 100% 0)',y:-20}:{clipPath:'inset(0 0 0 0)',y:0}} transition={{duration:reduced?0:.65,ease}} onAnimationComplete={()=>{if(closing){setSelected(null);setClosing(false)}}}><div className="modal-stage"><ProjectStage project={selected} priority/></div><div className="modal-copy"><p className="eyebrow">{settings.categories.find(c=>c.id===categoryKey(selected))?.name||selected.category}</p><DialogTitle>{selected.title}</DialogTitle><DialogDescription>{selected.description}</DialogDescription><div className="modal-links">{selected.url&&<a className="animated-link" href={selected.url} target="_blank" rel="noopener">Abrir projeto <ArrowUpRight size={18}/></a>}<a className="animated-link" href="#contacto" onClick={e=>{e.preventDefault();setSelected(null);setTimeout(()=>{lenis.current?.start();if(lenis.current)lenis.current.scrollTo('#contacto',{force:true});else document.getElementById('contacto')?.scrollIntoView()},0)}}>Pensar no meu projeto <ArrowUpRight size={18}/></a></div></div></motion.div>}</DialogContent></Dialog>
<Dialog open={privacy} onOpenChange={setPrivacy}><DialogContent className="privacy-modal" data-lenis-prevent><DialogTitle>Os seus dados.</DialogTitle><DialogDescription>O formulário prepara uma mensagem no seu aplicativo de email, sem guardar os campos no site. As informações enviadas são usadas para responder ao seu pedido. Não instalámos publicidade ou ferramentas de análise de visitas. A hospedagem, as fontes e os serviços de contacto têm as suas próprias práticas de tratamento de dados. A área de gestão usa autenticação e guarda o conteúdo do portfólio. Para questões sobre dados: {settings.text.contactEmail}.</DialogDescription></DialogContent></Dialog>
</div>}
