'use client';
import {defaultSettings,type SiteSettings} from '@/lib/site-content';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import {ProjectStage} from './project-stage';
import {discipline,projectMeta,type Project} from '@/lib/portfolio';
export function ServiceJourney({projects,onOpen,settings=defaultSettings}:{settings?:SiteSettings;projects:Project[];onOpen:(p:Project)=>void}){
const identity=projects.find(p=>p.id===settings.identityProject);const web=projects.find(p=>p.id===settings.websiteProject);const social=settings.socialProjects.map(id=>projects.find(p=>p.id===id)).filter((p):p is Project=>!!p);
return <section className="service-journey" id="servicos" aria-label="O que a Crisora faz"><div className="journey-top"><span>UMA PRESENÇA. TRÊS DIMENSÕES.</span><a href="#projetos">Ir para os projetos <ArrowDown size={16}/></a></div><div className="journey-scenes">
<article className="journey-scene identity-scene" data-chapter="0"><div className="chapter-copy"><p className="chapter-kicker">01 / O QUE TORNA A SUA MARCA RECONHECÍVEL</p><h2 className="chapter-title"><span><i>Identidade</i></span><span><i>visual.</i></span></h2><p className="chapter-description">{settings.text.identityDescription}</p><ul className="chapter-deliverables"><li>Logotipo & símbolo</li><li>Cores & tipografia</li><li>Manual & aplicações</li></ul><a className="animated-link chapter-cta" href="#contacto">Quero criar a minha identidade <ArrowUpRight size={18}/></a></div><div className="chapter-visual identity-system">{identity&&(identity.id!=='crisora'||identity.image!==projectMeta.crisora.image)?<ProjectStage project={identity}/>:<><div className="identity-signature story-piece"><img src="/assets/wordmark.92634bce5b.svg" alt="Assinatura visual da Crisora"/><span>01 — ASSINATURA</span></div><div className="identity-details"><div className="identity-letters story-piece"><span>Aa</span><p>Satoshi<br/><small>02 — TIPOGRAFIA</small></p></div><div className="identity-swatches story-piece"><div>{['#04102c','#6959fc','#2dd2cf','#f7f6f4'].map(c=><i style={{background:c}} key={c}/>)}</div><span>03 — PALETA DE CORES</span></div></div></>}{identity&&<button className="chapter-example" onClick={()=>onOpen(identity)}>Conhecer {identity.title} <ArrowUpRight size={17}/></button>}</div></article>
<article className="journey-scene website-scene" data-chapter="1"><div className="chapter-copy"><p className="chapter-kicker">02 / ONDE O SEU NEGÓCIO GANHA ESPAÇO</p><h2 className="chapter-title"><span><i>Websites.</i></span></h2><p className="chapter-description">{settings.text.websiteDescription}</p><ul className="chapter-deliverables"><li>Sites institucionais & portfólios</li><li>Landing pages & catálogos</li><li>Manutenção & assistência</li></ul><a className="animated-link chapter-cta" href="#contacto">Quero um site para a minha empresa <ArrowUpRight size={18}/></a></div><div className="chapter-visual website-system">{web&&<><div className="story-piece"><ProjectStage project={web}/></div><div className="website-delivery story-piece"><span>DESIGN + DESENVOLVIMENTO</span><p>Do primeiro ecrã<br/>ao próximo contacto.</p></div><button className="chapter-example" onClick={()=>onOpen(web)}>Conhecer o website {web.title} <ArrowUpRight size={17}/></button></>}</div></article>
<article className="journey-scene social-scene" data-chapter="2"><div className="chapter-copy"><p className="chapter-kicker">03 / COMO A SUA MARCA SE MANTÉM PRESENTE</p><h2 className="chapter-title"><span><i>Comunicação</i></span><span><i>digital.</i></span></h2><p className="chapter-description">{settings.text.socialDescription}</p><ul className="chapter-deliverables"><li>Design para redes sociais</li><li>Textos & conteúdos</li><li>Publicação & gestão</li></ul><a className="animated-link chapter-cta" href="#contacto">Quero melhorar a minha comunicação <ArrowUpRight size={18}/></a></div><div className="chapter-visual social-system"><div className="social-sheets">{social.map((p,i)=><button className={'story-piece social-sheet sheet-'+i} key={p.id} onClick={()=>onOpen(p)} aria-label={'Conhecer '+p.title}><img src={p.image} alt={p.title} loading="eager" decoding="async" width={1080} height={1350}/></button>)}</div><p className="chapter-example">Design & conteúdo para redes sociais</p></div></article>
</div><div className="journey-bottom"><nav aria-label="Capítulos dos serviços">{['Identidade visual','Websites','Comunicação digital'].map((t,i)=><button key={t} data-chapter-nav={i} onClick={()=>{const section=document.querySelector('.service-journey');if(!section?.classList.contains('is-directed'))section?.querySelectorAll('.journey-scene')[i]?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}}><span>0{i+1}</span>{t}</button>)}</nav><span className="journey-scroll">CONTINUE A DESCOBRIR ↓</span></div></section>
}
