export type Project={id:string;title:string;category:string;description:string;image:string;url:string;position:number;published:number;featured?:number};
export const initialProjects:Project[]=[
{id:'rony',title:'Rony Móveis',category:'Websites',description:'Site institucional e catálogo administrável. A experiência liga descoberta de produtos, filtros, seleção de peças e pedido de orçamento ao atendimento pelo WhatsApp. O painel permite à empresa cuidar do catálogo e dos pedidos.',image:'/assets/rony-campaign.4c8ef2489f.webp',url:'https://www.ronymoveis.com/',position:1,published:1},
{id:'patricia',title:'Patrícia Pradera',category:'Websites',description:'Demonstração de website para cabelo e maquilhagem. Fotografia, tipografia editorial e apresentação dos serviços constroem um percurso entre conhecer o trabalho e iniciar uma conversa. Proposta independente, não apresentada como site oficial.',image:'/assets/patricia-hero.1c39114a10.jpg',url:'https://cristianovieira24.github.io/patricia-pradera/',position:2,published:1},
{id:'liliana',title:'Liliana Pereira',category:'Websites',description:'Conceito independente de website institucional para uma solicitadora. A proposta organiza áreas de intervenção, percurso de atendimento e formas de contacto numa experiência editorial. Não representa o website oficial da profissional.',image:'/assets/liliana-portrait.e476eb3fc4.jpg',url:'https://liliana-pereira-solicitadora.vercel.app',position:3,published:1},
{id:'crisora',title:'Crisora',category:'Identidade visual',description:'A nossa própria identidade. Um sistema que combina assinatura, símbolo, paleta e tipografia para manter o reconhecimento da marca entre o site, as apresentações e a comunicação digital.',image:'/assets/wordmark.92634bce5b.svg',url:'',position:4,published:1},
{id:'fvl',title:'Clareza em primeiro plano',category:'Comunicação visual',description:'Um tema técnico, uma mensagem direta. Fotografia, contraste e hierarquia tornam a informação mais acessível. Peça de portfólio visual.',image:'/assets/fvl-cover.1809c69e3a.webp',url:'',position:5,published:1},
{id:'marcia',title:'Presença que inspira confiança',category:'Direção visual',description:'Uma abordagem editorial que aproxima imagem e conteúdo, com uma linguagem sóbria e consistente. Peça de portfólio visual.',image:'/assets/marcia-cover.82076080cc.webp',url:'',position:6,published:1},
{id:'cnh',title:'Uma mensagem impossível de ignorar',category:'Design de conteúdo',description:'Uma pergunta conduz a leitura. Escala, cor e composição ajudam a identificar o assunto num primeiro olhar. Peça de portfólio visual.',image:'/assets/cnh-cover.e942bc0bda.webp',url:'',position:7,published:1}];
export const projectMeta:Record<string,{label:string;preview?:string;image:string;scope:string[]}>={
rony:{label:'Site & catálogo',preview:'/previews/rony.html',image:'/assets/rony-campaign.4c8ef2489f.webp',scope:['Catálogo pesquisável','Seleção para orçamento','Painel de gestão']},
patricia:{label:'Demonstração de website',preview:'/previews/patricia.html',image:'/assets/patricia-hero.1c39114a10.jpg',scope:['Direção editorial','Portfólio de beleza','Apresentação de serviços']},
liliana:{label:'Conceito independente',preview:'/previews/liliana.html',image:'/assets/liliana-portrait.e476eb3fc4.jpg',scope:['Áreas de intervenção','Percurso de atendimento','Contacto direto']},
crisora:{label:'Identidade própria',image:'/assets/wordmark.92634bce5b.svg',scope:['Assinatura & símbolo','Sistema de cores','Tipografia Satoshi']}};
export function discipline(p:Project){if(p.category==='Websites'||p.url)return 'Websites';if(/identidade|branding/i.test(p.category))return 'Identidade';return 'Comunicação'}


const bundledImageVersions:Record<string,string>={"/assets/marcia-cover.webp": "/assets/marcia-cover.82076080cc.webp", "/assets/cnh-cover.webp": "/assets/cnh-cover.e942bc0bda.webp", "/assets/rony-logo.svg": "/assets/rony-logo.3a10f55aab.svg", "/assets/marcia.png": "/assets/marcia.14fb3a9068.png", "/assets/wordmark.svg": "/assets/wordmark.92634bce5b.svg", "/assets/logo.svg": "/assets/logo.9430607a47.svg", "/assets/living-surface.webp": "/assets/living-surface.730fdb508b.webp", "/assets/liliana-logo.jpg": "/assets/liliana-logo.a6247450f4.jpg", "/assets/rony-hero.webp": "/assets/rony-hero.fb8bf36f6b.webp", "/assets/crisora-material-clean.webp": "/assets/crisora-material-clean.95b886fb25.webp", "/assets/living-surface-clean.webp": "/assets/living-surface-clean.6ecf632dbc.webp", "/assets/crisora-material.webp": "/assets/crisora-material.9a6ff6331c.webp", "/assets/rony-campaign.webp": "/assets/rony-campaign.4c8ef2489f.webp", "/assets/hero.webp": "/assets/hero.68dace3487.webp", "/assets/symbol.svg": "/assets/symbol.577505649d.svg", "/assets/fvl.png": "/assets/fvl.fa5f9975e0.png", "/assets/immersive-flow.webp": "/assets/immersive-flow.1ebc43f150.webp", "/assets/cnh.png": "/assets/cnh.676939c0d3.png", "/assets/studio-optical.webp": "/assets/studio-optical.aa46fab1d8.webp", "/assets/fvl-cover.webp": "/assets/fvl-cover.1809c69e3a.webp", "/assets/liliana-portrait.jpg": "/assets/liliana-portrait.e476eb3fc4.jpg", "/assets/patricia-hero.jpg": "/assets/patricia-hero.1c39114a10.jpg"};
export function currentProjectImage(image:string){return bundledImageVersions[image]??image}
