import {z} from 'zod';
import type {Project} from './portfolio';
export const defaultCategories=[{id:'websites',name:'Websites'},{id:'identidade',name:'Identidade visual'},{id:'comunicacao',name:'Comunicação digital'}];
export function categoryKey(p:Pick<Project,'category'>){const c=p.category.trim();if(/^(sites|websites)$/i.test(c))return 'websites';if(/^(identidade visual|identidade|branding)$/i.test(c))return 'identidade';if(/^(comunicação visual|comunicação digital|direção visual|design de conteúdo|comunicação)$/i.test(c))return 'comunicacao';return c}
export const contentFields=[
 ['Início','heroLabel','Identificação','CRISORA · ESTÚDIO DE DESIGN'],['Início','heroLine1','Título · linha 1','A sua marca.'],['Início','heroLine2','Título · linha 2','Em outra dimensão.'],['Início','heroSubtitle','Subtítulo','Identidade visual. Websites. Comunicação digital.'],
 ['Serviços','identityDescription','Descrição de identidade','Criamos o logotipo, as cores e a tipografia que dão uma linguagem própria à sua empresa.'],['Serviços','websiteDescription','Descrição de websites','Criamos e desenvolvemos sites que apresentam a sua empresa, organizam os serviços e facilitam o contacto.'],['Serviços','socialDescription','Descrição de comunicação','Planeamos, escrevemos e criamos o conteúdo que liga a sua marca às pessoas. Com consistência, do perfil à publicação.'],
 ['Portfólio','portfolioTitle','Título','Projetos selecionados.'],['Portfólio','portfolioDescription','Introdução','Conheça o trabalho por área.'],
 ['A Crisora','studioLine1','Título · linha 1','Entre o que é.'],['A Crisora','studioLine2','Título · linha 2','E o que se percebe.'],['A Crisora','studioDescription1','Texto 1','É nesse encontro que trabalhamos. Uma identidade que representa, um site que aproxima e uma comunicação que faz sentido para quem chega.'],['A Crisora','studioDescription2','Texto 2','Começamos por compreender a empresa. A partir daí, ligamos imagem, mensagem e experiência numa direção comum.'],
 ['Contacto','contactLine1','Título · linha 1','Vamos dar forma'],['Contacto','contactLine2','Título · linha 2','à sua próxima ideia?'],['Contacto','contactDescription','Introdução','Conte-nos o que faz a sua empresa e o que gostaria de criar ou melhorar.'],['Contacto','contactEmail','Email','cristiano.silva.vieira24@gmail.com'],['Contacto','contactInstagram','Instagram','https://www.instagram.com/crisoradesign/'],['Contacto','contactLocale','Área de atendimento','BRASIL & PORTUGAL · ATENDIMENTO ONLINE'],
] as const;
export const defaultSettings={categories:defaultCategories,text:Object.fromEntries(contentFields.map(([,key,,value])=>[key,value])) as Record<string,string>,heroImage:'/assets/living-surface-clean.6ecf632dbc.webp',backgroundImage:'/assets/immersive-flow.1ebc43f150.webp',studioImage:'',websiteProject:'rony',identityProject:'crisora',socialProjects:['fvl','marcia','cnh'],process:[['Conversar','Conhecemos o negócio, o seu momento e o que precisa de evoluir.'],['Alinhar','Uma proposta com direção, entregas, investimento e prazo.'],['Dar forma','Desenvolvemos o projeto, apresentamos e afinamos as escolhas.'],['Acompanhar','Entrega, orientação e a assistência prevista na proposta.']],faq:[['Podemos começar por apenas um serviço?','Sim. Pode contratar um site, uma identidade ou um projeto de comunicação. A proposta responde ao momento e às prioridades do negócio.'],['Como definimos investimento e prazo?','Depois de compreender o projeto, apresentamos as entregas, o investimento, o prazo e as condições. Tudo é alinhado antes de avançar.'],['E depois da entrega?','Os ajustes, arquivos finais, domínio, hospedagem e acompanhamento são definidos na proposta. Podemos manter a assistência conforme as necessidades do projeto.'],['Como funciona o atendimento?','O atendimento é totalmente online, no Brasil e em Portugal. Começamos por mensagem e, quando necessário, organizamos uma reunião.']]};
export type SiteSettings=typeof defaultSettings;
const image=z.string().regex(/^\/(assets|media)\/[\w.-]+$/);const pair=z.array(z.string().trim().min(1).max(3000)).length(2);
export const settingsSchema=z.object({categories:z.array(z.object({id:z.string().min(1).max(80),name:z.string().trim().min(1).max(60)})).min(1).max(30),text:z.record(z.string(),z.string().max(3000)).refine(t=>contentFields.every(([,k])=>typeof t[k]==='string'&&t[k].trim().length>0),'Preencha todos os textos.').refine(t=>z.string().email().safeParse(t.contactEmail).success,'Email inválido.').refine(t=>/^https:\/\/(www\.)?instagram\.com\/[\w.]+\/?$/.test(t.contactInstagram),'Use um endereço de perfil Instagram válido.'),heroImage:image,backgroundImage:image,studioImage:z.union([image,z.literal('')]),websiteProject:z.string().max(80),identityProject:z.string().max(80),socialProjects:z.array(z.string().max(80)).max(3),process:z.array(pair).min(1).max(8),faq:z.array(pair).max(12)}).refine(s=>new Set(s.categories.map(c=>c.id)).size===s.categories.length,'Categorias duplicadas.');
export function availableCategories(settings:SiteSettings,projects:Project[]){const list=[...settings.categories];for(const p of projects){const id=categoryKey(p);if(!list.some(c=>c.id===id))list.push({id,name:p.category})}return list}
export function selectedProjects(projects:Project[],category:string,full=false){const matching=projects.filter(p=>p.published&&categoryKey(p)===category).sort((a,b)=>a.position-b.position||a.title.localeCompare(b.title));return full?matching:matching.filter(p=>p.featured!==0).slice(0,6)}

